[package]
name = "wf"
version = "0.1.0"
authors = ["Richard Feldman <richard.t.feldman@gmail.com>"]

[dependencies]
byteorder = "1.2.7"

[dependencies.clap]
version = "~2.32.0"
default-features = false

[dev-dependencies]
maplit = "1.0.1"
tempfile = "3.0.4"
